[package]
# Do not change the name of this crate.
name = "hub"
version = "0.1.0"
edition = "2021"

[lib]
# `lib` is required for non-library targets,
# such as tests and benchmarks.
# `cdylib` is for Linux, Android, Windows, and web.
# `staticlib` is for iOS and macOS.
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
rinf = "7.3.1"
prost = "0.13.0"
tokio = { version = "1", features = ["sync", "rt", "macros", "time"] }

# Uncomment below to target the web.
# tokio_with_wasm = { version = "0.8.1", features = ["rt", "macros"] }
# wasm-bindgen = "0.2.95"
